services:
  - type: web
    name: chinese-poker
    env: python
    region: frankfurt  # или другой ближайший регион
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 1 --timeout 120 --access-logfile - --error-logfile - --log-level debug wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
